CREATE TABLE locale
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street      VARCHAR(255)                            NOT NULL,
    complement  VARCHAR(255),
    number      VARCHAR(255)                            NOT NULL,
    city        VARCHAR(255)                            NOT NULL,
    state       VARCHAR(255)                            NOT NULL,
    zip_code    VARCHAR(255)                            NOT NULL,
    external_id UUID,
    CONSTRAINT pk_locale PRIMARY KEY (id)
);

ALTER TABLE locale
    ADD CONSTRAINT uc_locale_external UNIQUE (external_id);


CREATE TABLE sport
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    external_id UUID,
    CONSTRAINT pk_sport PRIMARY KEY (id)
);

ALTER TABLE sport
    ADD CONSTRAINT uc_sport_external UNIQUE (external_id);


CREATE TABLE gym
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    rules       TEXT,
    locale_id   BIGINT,
    gym_access  VARCHAR(255)                            NOT NULL,
    external_id UUID,
    CONSTRAINT pk_gym PRIMARY KEY (id)
);

ALTER TABLE gym
    ADD CONSTRAINT uc_gym_external UNIQUE (external_id);

ALTER TABLE gym
    ADD CONSTRAINT FK_GYM_ON_LOCALE FOREIGN KEY (locale_id) REFERENCES locale (id);

CREATE TABLE practicable
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    sport_id            BIGINT                                  NOT NULL,
    gym_id              BIGINT                                  NOT NULL,
    availability_status VARCHAR(255)                            NOT NULL,
    external_id         UUID,
    CONSTRAINT pk_practicable PRIMARY KEY (id)
);

ALTER TABLE practicable
    ADD CONSTRAINT uc_practicable_external UNIQUE (external_id);

ALTER TABLE practicable
    ADD CONSTRAINT FK_PRACTICABLE_ON_GYM FOREIGN KEY (gym_id) REFERENCES gym (id);

ALTER TABLE practicable
    ADD CONSTRAINT FK_PRACTICABLE_ON_SPORT FOREIGN KEY (sport_id) REFERENCES sport (id);