CREATE TABLE address
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    street      VARCHAR(255)                            NOT NULL,
    complement  VARCHAR(255),
    number      VARCHAR(255)                            NOT NULL,
    city        VARCHAR(255)                            NOT NULL,
    state       VARCHAR(255)                            NOT NULL,
    zip_code    VARCHAR(255)                            NOT NULL,
    external_id UUID,
    CONSTRAINT pk_address PRIMARY KEY (id)
);

ALTER TABLE address
    ADD CONSTRAINT uc_address_external UNIQUE (external_id);

CREATE TABLE team
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    description TEXT,
    owner_id    BIGINT,
    external_id UUID,
    CONSTRAINT pk_team PRIMARY KEY (id)
);


CREATE TABLE athlete
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name           VARCHAR(255) NOT NULL,
    social_name         VARCHAR(255),
    birth_date          date         NOT NULL,
    cpf                 VARCHAR(11),
    external_id         UUID,
    address_id          BIGINT       NOT NULL,
    weight              DOUBLE PRECISION,
    height              DOUBLE PRECISION,
    biceps_measurement  DOUBLE PRECISION,
    forearm_measurement DOUBLE PRECISION,
    chest_measurement   DOUBLE PRECISION,
    thigh_measurement   DOUBLE PRECISION,
    calf_measurement    DOUBLE PRECISION,
    CONSTRAINT pk_athlete PRIMARY KEY (id)
);

create TABLE membership
(
    athlete_id BIGINT NOT NULL,
    team_id BIGINT NOT NULL,
    profile varchar(100),
    status varchar(100),
    constraint pk_athlete PRIMARY KEY(athlete_id, team_id)
);



alter table membership
    add constraint FK_MEMBERSHIP_ON_ATHLETE FOREIGN KEY (athlete_id) references athlete(id),
    add constraint FK_MEMBERSHIP_ON_TEAM foreign key (team_id) references team(id);

ALTER TABLE athlete
    ADD CONSTRAINT uc_athlete_external UNIQUE (external_id);

ALTER TABLE athlete
    ADD CONSTRAINT FK_ATHLETE_ON_ADDRESS FOREIGN KEY (address_id) REFERENCES address (id);

ALTER TABLE team
    ADD CONSTRAINT uc_team_external UNIQUE (external_id);

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_OWNER FOREIGN KEY (owner_id) REFERENCES athlete (id);